transports:
- name: local0
  protocol: mqtt
  broker:
    address: tcp://localhost:1883
    # username: username
    # password: password
- name: local1
  protocol: mqtt
  broker:
    address: tcp://localhost:1883

routes:
  local0_to_local1:
    connector: local0
    topics:
    - "hello.world"
    endpoints:
    - transport: local1
      # rewrite:
