transports:
- name: local
  protocol: mqtt
  broker:
    address: tcp://localhost:1883
    # username: username
    # password: password
- name: mqtt
  protocol: mqtt
  broker:
    address: tcp://mqtt.example:1883
- name: nats
  protocol: nats
  broker:
    address: nats://nats.example:4222
    opts:
      pull: true
      jetstream:
        events:
          stream:
            name: EVENTS
            config: |
              {
                "description": "events",
                "subjects": [
                  "events.>"
                ]
              }
          consumer:
            name: instance-0
            stream: EVENTS
            config: |
              {
                "ack_policy": "explicit"
              }

persistences:
- name: events
  driver: badger
  # dsn: $FORWARDER_PATH/events

# TODO: middlewares

routes:
  local_to_mqtt:
    connector: local
    topics:
    - "hello.world"
    endpoints:
    - mqtt
    - events
  nats_to_local:
    connector: nats
    topics:
    - "events::#"
    endpoints: [ local ]
